service: shopX-information

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 512
  stage: dev
  region: ap-south-1

functions:
  gis-authorizer:
    handler: dist/authorizer/index.handler
  business:
    handler: dist/business/index.handler
    events:
      - http:
          path: /api/user/{userId}/cart
          method: GET
          authorizer: gis-authorizer
      - http:
          path: /api/user/{userId}/cart
          method: POST
          authorizer: gis-authorizer

package:
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - src/**
    - docs/**
    - package-lock.json
    - package.json
    - tsconfig.json